/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CategoryList: typeof import('./src/components/CategoryList.vue')['default']
    ChoicesSelect: typeof import('./src/components/ChoicesSelect.vue')['default']
    CustomizerOption: typeof import('./src/components/CustomizerOption.vue')['default']
    CustomizerSelect: typeof import('./src/components/CustomizerSelect.vue')['default']
    IJamDiscord: typeof import('~icons/jam/discord')['default']
    PresetMode: typeof import('./src/components/PresetMode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideToggle: typeof import('./src/components/SlideToggle.vue')['default']
  }
}
